export enum CommonCode {
  USER_ROLES = 'USER_ROLES',
  USER_STATUS = 'USER_STATUS',
  PRODUCT_CATEGORIES = 'PRODUCT_CATEGORIES',
  ROUTES = 'ROUTES',
  ITEMS = 'ITEMS',
  BATCH = 'BATCH',
  CUSTOMER = 'CUSTOMER',
  VEHICLE = 'VEHICLE',
  STOCK = 'STOCK',
  SALESSTOCK = 'SALESSTOCK',
  RETURN = 'RETURN',
}
